# 本地HTTP(S)端口
# port: 7890

# 本地SOCKS5端口
# socks-port: 7891

# 透明代理端口Linux and macOS (Redirect TCP and TProxy UDP)
# redir-port: 7892

# 透明代理端口Linux (TProxy TCP and TProxy UDP)
# tproxy-port: 7893

# HTTP(S)和SOCKS5同一端口
mixed-port: 7890

# 允许LAN上的其他设备通过Clash访问Internet。
allow-lan: true

# 通过具有特定IP地址的lan访问
# "*": 绑定所有IP地址
# 192.168.122.11: 绑定单个IPv4地址
# "[aaaa::a8aa:ff:fe09:57d8]": 绑定单个IPv6地址
bind-address: "*"

# 本地SOCKS5/HTTP（S）服务器的身份验证
# authentication: 
#   - "user1:password1"
#   - "user2:word2"

# Clash 模式选择
# global 全局模式
# rule   规则模式 (默认) 
# direct 直连模式
# script 脚本模式
mode: rule

# Clash核心的日志级别 
# Debug 将显示所有DNS查询和提供程序更新日志
# Debug 不会引起任何性能问题
# silent   静默
# error    错误
# warning  警告
# info     信息
# debug    调试
log-level: debug

# 外部控制器可以通过 RESTful API 从外部控制Clash
external-controller: 0.0.0.0:9090
# RESTful API的密码 (可选)
secret: '123456'

# 您可以将静态web资源(如clash dashboar)放到一个目录中,clash将在${API}/ui中提供服务
# 输入是配置目录的相对路径或绝对路径
# external-ui: folder

# 出站接口名称
# interface-name: eth0

# 实验性选择
experimental:
# 将忽略dns解析失败,继续匹配规则,默认值为true
  ignore-resolve-fail: true

# 将在启动请求时连接到ipv6地址
# 默认值为false,它只建立到v4地址的连接。
ipv6: false

# 开启系统代理时将忽略这些域(或ip地址)
cfw-bypass:
  - "<local>"
  - 10.*
  - 127.*
  - 172.16.*
  - 172.17.*
  - 172.18.*
  - 172.19.*
  - 172.20.*
  - 172.21.*
  - 172.22.*
  - 172.23.*
  - 172.24.*
  - 172.25.*
  - 172.26.*
  - 172.27.*
  - 172.28.*
  - 172.29.*
  - 172.30.*
  - 172.31.*
  - 192.168.*
  - localhost

# cfw仅有 
# 延迟测试设置
# 超时时间 单位秒
cfw-latency-timeout: 3000

# cfw仅有
# 测试网址
cfw-latency-url: http://cp.cloudflare.com/generate_204

# cfw仅有
# 更换节点 配置文件 模式 是否打断连接
# proxy   none(不切换) chain(连接中的代理组) all(全部)
# profile true(文件切换断开连接) false(不断开连接)
# mode    true(切换模式断开连接) false(不断开连接)
cfw-conn-break-strategy:
  proxy: all
  profile: true
  mode: true

# cfw仅有
# 排序规则
# default  默认
# latency  延迟
# alphabet 字母
cfw-proxies-order: default

# DNS服务器
dns:
  # 开启Clash内置DNS服务器
  # 默认为false
  enable: true
  # 不使用ipv6解析
  # 默认为false
  ipv6: false
  # DNS监听端口
  listen: 0.0.0.0:7874
  # 解析nameserver和fallback的DNS服务器
  # 填入纯IP的DNS服务器
  default-nameserver:
    - 114.114.114.114
    - 180.76.76.76
    - 8.8.8.8
  # 模式fake-ip  or  redir-host
  enhanced-mode: redir-host
  # 使用本地hosts文件
  use-hosts: true
  # 国内用下列DNS解析
  nameserver:
    - 101.6.6.6
    - tls://dns.alidns.com
    - tls://doh.pub
    - tls://dns.pub
    - tls://dot.360.cn
    - tls://dns.cfiec.net
    - https://dns.alidns.com/dns-query
    - https://doh.pub/dns-query
    - https://dns.pub/dns-query
    - https://doh.360.cn/dns-query
    - https://dns.cfiec.net/dns-query
    - https://rubyfish.cn/dns-query
    - https://dns.rubyfish.cn/dns-quer
  # 国内用下列DNS解析
  fallback:
    - tls://dns.google
    - tls://1dot1dot1dot1.cloudflare-dns.com
    - tls://one.one.one.one
    - tls://dot.sb
    - https://dns.google/dns-query
    - https://dns.google/resolve
    - https://dns.quad9.net/dns-query
    - https://dns11.quad9.net/dns-query
    - https://doh.opendns.com/dns-query
    - https://doh.familyshield.opendns.com/dns-query
    - https://cloudflare-dns.com/dns-query
    - https://1.1.1.1/dns-query
    - https://1.0.0.1/dns-query
    - https://dns.adguard.com/dns-query
    - https://dns-family.adguard.com/dns-query
    - https://doh.dns.sb/dns-query
    - https://doh.cleanbrowsing.org/doh/family-filter/
    - https://doh.powerdns.org
    - https://public.dns.iij.jp/dns-query
    - https://doh-jp.blahdns.com/dns-query
    - https://dns64.dns.google/dns-query
  # fake-ip仅有
  fake-ip-filter:
    - "*.lan"
    - "*.localdomain"
    - "*.example"
    - "*.invalid"
    - "*.localhost"
    - "*.test"
    - "*.local"
    - "*.home.arpa"
    - "time.*.com"
    - "time.*.gov"
    - "time.*.edu.cn"
    - "time.*.apple.com"
    - "time1.*.com"
    - "time2.*.com"
    - "time3.*.com"
    - "time4.*.com"
    - "time5.*.com"
    - "time6.*.com"
    - "time7.*.com"
    - "ntp.*.com"
    - "ntp1.*.com"
    - "ntp2.*.com"
    - "ntp3.*.com"
    - "ntp4.*.com"
    - "ntp5.*.com"
    - "ntp6.*.com"
    - "ntp7.*.com"
    - "*.time.edu.cn"
    - "*.ntp.org.cn"
    - "+.pool.ntp.org"
    - "time1.cloud.tencent.com"
    - "music.163.com"
    - "*.music.163.com"
    - "*.126.net"
    - "musicapi.taihe.com"
    - "music.taihe.com"
    - "songsearch.kugou.com"
    - "trackercdn.kugou.com"
    - "*.kuwo.cn"
    - "api-jooxtt.sanook.com"
    - "api.joox.com"
    - "joox.com"
    - "y.qq.com"
    - "*.y.qq.com"
    - "streamoc.music.tc.qq.com"
    - "mobileoc.music.tc.qq.com"
    - "isure.stream.qqmusic.qq.com"
    - "dl.stream.qqmusic.qq.com"
    - "aqqmusic.tc.qq.com"
    - "amobile.music.tc.qq.com"
    - "*.xiami.com"
    - "*.music.migu.cn"
    - "music.migu.cn"
    - "*.msftconnecttest.com"
    - "*.msftncsi.com"
    - "msftconnecttest.com"
    - "msftncsi.com"
    - "localhost.ptlogin2.qq.com"
    - "localhost.sec.qq.com"
    - "+.srv.nintendo.net"
    - "+.stun.playstation.net"
    - "xbox.*.microsoft.com"
    - "xnotify.xboxlive.com"
    - "+.battlenet.com.cn"
    - "+.wotgame.cn"
    - "+.wggames.cn"
    - "+.wowsgame.cn"
    - "+.wargaming.net"
    - "proxy.golang.org"
    - "stun.*.*"
    - "stun.*.*.*"
    - "+.stun.*.*"
    - "+.stun.*.*.*"
    - "+.stun.*.*.*.*"
    - "heartbeat.belkin.com"
    - "*.linksys.com"
    - "*.linksyssmartwifi.com"
    - "*.router.asus.com"
    - "mesu.apple.com"
    - "swscan.apple.com"
    - "swquery.apple.com"
    - "swdownload.apple.com"
    - "swcdn.apple.com"
    - "swdist.apple.com"
    - "lens.l.google.com"
    - "stun.l.google.com"
    - "+.nflxvideo.net"
    - "*.square-enix.com"
    - "*.finalfantasyxiv.com"
    - "*.ffxiv.com"
  # fake-ip仅有
  fallback-filter:
    geoip: false
    ipcidr:
      - 0.0.0.0/8
      - 10.0.0.0/8
      - 100.64.0.0/10
      - 127.0.0.0/8
      - 169.254.0.0/16
      - 172.16.0.0/12
      - 192.0.0.0/24
      - 192.0.2.0/24
      - 192.168.0.0/16
      - 192.88.99.0/24
      - 198.18.0.0/15
      - 198.51.100.0/24
      - 203.0.113.0/24
      - 224.0.0.0/4
      - 240.0.0.0/4
      - 255.255.255.255/32
    domain:
      - '+.facebook.com'
      - '+.githubusercontent.com'
      - '+.google.com'
      - '+.youtube.com'
  
# clash-for-android: 
  # 追加系统 DNS 到 nameserver 
  # append-system-dns: true 
  # ui-subtitle-pattern: "[\u4e00-\u9fa5]{2,4}"